import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  container: {
    flex: 1,
      backgroundColor: '#fff',
      paddingVertical: 40,
  },
  header: {
    width: '100%',
    height: 60,
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingHorizontal: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
  },
  profile: {
    width: 37,
    height: 39,
    tintColor:'#0262A6'
  },
  cardcontainer:{
    width:350,
    height:400,
    justifyContent:'center',
    alignItems:'center',
    flexDirection:'column',
    marginLeft:-8,
    padding: 10,
    marginHorizontal: 30,
    marginVertical: '20%',
    maxWidth: 3000,
    maxHeight: 3000,
  },
  card: {
     backgroundColor: '#e6f2ff',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    width:295,
    height:318, 
    padding: 20,
    marginHorizontal: 10,
    marginVertical: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#007bff',
    marginBottom: 10,
  },
  companyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  logo: {
    width: 40,
    height: 40,
    marginRight: 10,
  },
  companyName: {
    fontSize: 18,
    color: '#333',
    fontWeight: 'bold',
  },
  location: {
    fontSize: 16,
    color: '#666',
    marginVertical: 5,
  },
  matchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  matchIcon: {
    width: 20,
    height: 20,
    borderRadius: 10,
    marginRight: 10,
  },
  matchMessage: {
    fontSize: 16,
    color: '#007bff',
  },
  datePosted: {
    fontSize: 14,
    color: '#999',
  },
  detailsLink: {
    color: '#007bff',
    fontWeight: 'bold',
    marginTop: 10,
    fontSize:18,
    textDecorationLine:'underline',
    textAlign: 'right',
  },
  navbar: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems:'center',
    paddingVertical: 10,
    backgroundColor: '#007bff',
    position: 'absolute',
    bottom: 0,
    width: '100%',
  },
  navItem: {
    flex: 1,
    alignItems: 'center',
    padding:1,
  },
  navItemContent: {
    alignItems: 'center', // Centraliza o conteúdo (ícone + texto)
    justifyContent: 'center',
  },
  icon: {
    width: 30,
    height: 30,
    alignItems:'center',
    justifyContent:'center',
    tintColor: '#fff',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#007bff',
  },
  textHome:{
    color:'white',
    fontSize:12,
  },
});